topFilms = ["The Matrix", "The Hunger Games", "Taken"];
console.log(topFilms[0]);
console.log(topFilms[1]);
console.log(topFilms[2]);
topGames = ["Red Dead Redemption 2", "Gta V", "Far Cry Primal"];
console.log(topGames[0]);
console.log(topGames[1]);
console.log(topGames[2]);
topFruit = ["Banaan", "Kiwi", "Perzik"];
console.log(topFruit[0]);
console.log(topFruit[1]);
console.log(topFruit[2]);